package app.bibifoq.core.net

/**
 * Reads and writes the Netscape `cookies.txt` format.
 *
 * This format is the interchange point, and that is the whole reason to use it: the extraction
 * engine accepts exactly this file via `--cookies`, and the app's own HTTP client can be taught
 * to read the same one. A single file means a site you signed into works on both the fast
 * native path and the engine path, instead of only one of them.
 *
 * Tab-separated, seven fields:
 * `domain  includeSubdomains  path  secure  expiresAtSeconds  name  value`
 */
object NetscapeCookies {

    const val HEADER: String = "# Netscape HTTP Cookie File"

    /** curl and yt-dlp both mark http-only cookies with this comment prefix rather than a field. */
    private const val HTTP_ONLY_PREFIX = "#HttpOnly_"

    fun parse(text: String): List<StoredCookie> = text.lineSequence().mapNotNull(::parseLine).toList()

    internal fun parseLine(rawLine: String): StoredCookie? {
        val line = rawLine.trim()
        if (line.isEmpty()) return null

        val httpOnly = line.startsWith(HTTP_ONLY_PREFIX)
        // Every other comment really is a comment.
        if (line.startsWith("#") && !httpOnly) return null

        val body = if (httpOnly) line.removePrefix(HTTP_ONLY_PREFIX) else line
        val fields = body.split('\t')
        if (fields.size < 7) return null

        val name = fields[5]
        if (name.isBlank()) return null

        return StoredCookie(
            domain = fields[0].lowercase(),
            includeSubdomains = fields[1].equals("TRUE", ignoreCase = true),
            path = fields[2].ifBlank { "/" },
            secure = fields[3].equals("TRUE", ignoreCase = true),
            // 0 means a session cookie: no expiry, gone when the browser closes.
            expiresAtSeconds = fields[4].toLongOrNull() ?: 0L,
            name = name,
            // Values may legitimately contain "=" and spaces; only tabs are structural.
            value = fields.drop(6).joinToString("\t"),
            httpOnly = httpOnly,
        )
    }

    /**
     * Converts a browser's `Cookie:` header into stored cookies for [host].
     *
     * This is what a WebView hands back after a sign-in: names and values only, with none of
     * the metadata. Everything else has to be assumed, so the assumptions are made explicit
     * and conservative - scoped to the host's registrable domain, marked secure, and given a
     * finite lifetime rather than pretending to know the real one.
     */
    fun fromBrowserCookieHeader(
        host: String,
        header: String,
        expiresAtSeconds: Long,
    ): List<StoredCookie> {
        val domain = host.lowercase().removePrefix("www.")
        return header.split(';')
            .mapNotNull { pair ->
                val trimmed = pair.trim()
                if (trimmed.isEmpty()) return@mapNotNull null
                val separator = trimmed.indexOf('=')
                if (separator <= 0) return@mapNotNull null
                StoredCookie(
                    domain = ".$domain",
                    includeSubdomains = true,
                    path = "/",
                    secure = true,
                    expiresAtSeconds = expiresAtSeconds,
                    name = trimmed.substring(0, separator).trim(),
                    value = trimmed.substring(separator + 1).trim(),
                )
            }
            .filter { it.name.isNotBlank() }
    }

    fun serialize(cookies: List<StoredCookie>): String = buildString {
        appendLine(HEADER)
        appendLine("# Generated by Bibifoq. Editing this file by hand is supported.")
        cookies.forEach { cookie ->
            if (cookie.httpOnly) append(HTTP_ONLY_PREFIX)
            append(cookie.domain)
            append('\t').append(if (cookie.includeSubdomains) "TRUE" else "FALSE")
            append('\t').append(cookie.path)
            append('\t').append(if (cookie.secure) "TRUE" else "FALSE")
            append('\t').append(cookie.expiresAtSeconds)
            append('\t').append(cookie.name)
            append('\t').append(cookie.value)
            appendLine()
        }
    }
}

/** One cookie as the file stores it. */
data class StoredCookie(
    val domain: String,
    val includeSubdomains: Boolean,
    val path: String,
    val secure: Boolean,
    /** Unix seconds, or 0 for a session cookie. */
    val expiresAtSeconds: Long,
    val name: String,
    val value: String,
    val httpOnly: Boolean = false,
) {
    fun isExpired(nowSeconds: Long): Boolean =
        expiresAtSeconds != 0L && expiresAtSeconds <= nowSeconds

    /**
     * Whether this cookie should be sent to [host].
     *
     * Deliberately strict about the suffix check: matching "evilexample.com" against a cookie
     * for "example.com" would hand someone else's session to the wrong server.
     */
    fun matchesHost(host: String): Boolean {
        val target = host.lowercase()
        val owner = domain.removePrefix(".").lowercase()
        if (target == owner) return true
        if (!includeSubdomains && !domain.startsWith(".")) return false
        return target.endsWith(".$owner")
    }

    fun matchesPath(requestPath: String): Boolean {
        val cookiePath = path.ifBlank { "/" }
        if (cookiePath == "/") return true
        if (requestPath == cookiePath) return true
        return requestPath.startsWith(
            if (cookiePath.endsWith("/")) cookiePath else "$cookiePath/",
        )
    }
}
